version: '3'

services:
  ipython:
    image: probabilistic/ipython_pyro
    ports:
      - 8888:8888
    environment:
      - NB_USER=paulina
      - NB_UID=1001
    working_dir: /home/paulina
    user: root
    volumes:
      - ./data:/home/paulina
    